# LICENSE HEADER MANAGED BY add-license-header
#
# BSD 3-Clause License
#
# Copyright (c) 2026, Martin Vesterlund
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

"""Normalization helpers for scenario drafts generated by LLM providers."""

import re
import unicodedata
from typing import Any

from src.logging_utils import get_logger


logger = get_logger(__name__)

SCENARIO_LIST_FIELDS = (
    "actors",
    "inject_catalog",
    "text_matchers",
    "target_aliases",
    "interpretation_hints",
    "rules",
    "executable_rules",
)
SCENARIO_ENTITY_ID_FIELDS = (
    ("actors", "actor"),
    ("inject_catalog", "inject"),
    ("text_matchers", "matcher"),
    ("target_aliases", "alias"),
    ("interpretation_hints", "hint"),
    ("rules", "rule"),
)
ALLOWED_RULE_FACTS = {
    "state.phase",
    "state.no_communication_turns",
    "state.metrics.impact_level",
    "state.metrics.media_pressure",
    "state.metrics.service_disruption",
    "state.metrics.leadership_pressure",
    "state.metrics.public_confusion",
    "state.metrics.attack_surface",
    "state.flags.executive_escalation",
    "state.flags.external_comms_sent",
    "state.flags.forensic_analysis_started",
    "state.flags.external_access_restricted",
    "session.turn_number",
    "action.action_types",
    "action.targets",
}
ALLOWED_RULE_OPERATORS = {
    "equals",
    "not_equals",
    "gte",
    "lte",
    "contains",
    "not_contains",
}
ALLOWED_METRIC_PATHS = {
    "state.metrics.impact_level",
    "state.metrics.media_pressure",
    "state.metrics.service_disruption",
    "state.metrics.leadership_pressure",
    "state.metrics.public_confusion",
    "state.metrics.attack_surface",
}
ALLOWED_FLAG_PATHS = {
    "state.flags.executive_escalation",
    "state.flags.external_comms_sent",
    "state.flags.forensic_analysis_started",
    "state.flags.external_access_restricted",
}
DEFAULT_STATE_DECISION = (
    "Vilken åtgärd eller prioritering behöver beslutas i detta läge?"
)
DEFAULT_STATE_NOTES = (
    "Narrativet omvandlades automatiskt från fritext till giltig struktur."
)


def normalize_scenario_payload(payload: dict[str, Any]) -> dict[str, Any]:
    """Best-effort normalization for scenario drafts returned by an LLM."""

    normalized = dict(payload)
    if isinstance(normalized.get("id"), str):
        normalized["id"] = _sanitize_identifier(
            normalized["id"], fallback="scenario-draft"
        )

    for list_field in SCENARIO_LIST_FIELDS:
        value = normalized.get(list_field)
        if value is None:
            normalized[list_field] = []

    rules = normalized.get("rules")
    normalized_rules = list(rules) if isinstance(rules, list) else []
    known_phases = _normalize_states(normalized)
    _ensure_initial_state_complete(normalized)
    for field_name, fallback_prefix in SCENARIO_ENTITY_ID_FIELDS:
        _normalize_entity_ids(normalized, field_name, fallback_prefix=fallback_prefix)

    executable_rules = normalized.get("executable_rules")
    if isinstance(executable_rules, list):
        valid_executable_rules: list[Any] = []
        downgraded_count = 0
        seen_rule_ids: set[str] = set()

        for index, rule in enumerate(executable_rules):
            normalized_rule = _normalize_executable_rule(
                rule,
                index=index,
                seen_rule_ids=seen_rule_ids,
                known_phases=known_phases,
            )
            if normalized_rule is None:
                downgraded_count += 1
                continue

            if _is_valid_executable_rule(normalized_rule):
                valid_executable_rules.append(normalized_rule)
                continue

            downgraded_count += 1
            normalized_rules.append(
                _downgrade_rule_to_documentation(normalized_rule, index=index)
            )

        if downgraded_count:
            logger.warning(
                "Scenario payload contained %s incomplete executable_rules; downgraded them to documentation rules",
                downgraded_count,
            )

        normalized["executable_rules"] = valid_executable_rules

    normalized["rules"] = normalized_rules
    return normalized


def _normalize_states(payload: dict[str, Any]) -> set[str]:
    states = payload.get("states")
    if not isinstance(states, list):
        return set()

    seen_state_ids: set[str] = set()
    seen_phases: set[str] = set()
    known_phases: set[str] = set()

    for index, state in enumerate(states):
        if not isinstance(state, dict):
            continue

        title = str(state.get("title") or "")
        fallback_state_id = (
            f"state-{_sanitize_identifier(title, fallback=f'phase-{index + 1}')}"
        )
        state["id"] = _ensure_unique_identifier(
            _sanitize_identifier(
                str(state.get("id") or fallback_state_id),
                fallback=fallback_state_id,
            ),
            seen_state_ids,
        )

        phase_seed = state.get("phase") or title or f"phase-{index + 1}"
        state["phase"] = _ensure_unique_identifier(
            _sanitize_identifier(str(phase_seed), fallback=f"phase-{index + 1}"),
            seen_phases,
        )
        _normalize_state_narration(state)
        known_phases.add(state["phase"])

    return known_phases


def _ensure_initial_state_complete(payload: dict[str, Any]) -> None:
    states = payload.get("states")
    if not isinstance(states, list) or not states or not isinstance(states[0], dict):
        return

    initial_state = states[0]
    source_text = payload.get("original_text")

    if (
        not isinstance(initial_state.get("time"), str)
        or not initial_state.get("time").strip()
    ):
        initial_state["time"] = _extract_time_from_text(source_text) or "08:00"

    impact_level = initial_state.get("impact_level")
    if not isinstance(impact_level, int) or not (1 <= impact_level <= 5):
        initial_state["impact_level"] = 3

    narration = initial_state.get("narration")
    if not isinstance(narration, dict) or not narration:
        initial_state["narration"] = _build_default_state_narration(initial_state)
        return

    default_narration = narration.get("default")
    by_audience = narration.get("by_audience")
    has_default = isinstance(default_narration, dict)
    has_by_audience = isinstance(by_audience, dict) and bool(by_audience)
    if not has_default and not has_by_audience:
        initial_state["narration"] = _build_default_state_narration(initial_state)


def _extract_time_from_text(source_text: Any) -> str | None:
    if not isinstance(source_text, str):
        return None

    match = re.search(r"\b([01]?\d|2[0-3]):([0-5]\d)\b", source_text)
    if not match:
        return None

    hour = int(match.group(1))
    minute = int(match.group(2))
    return f"{hour:02d}:{minute:02d}"


def _build_default_state_narration(state: dict[str, Any]) -> dict[str, Any]:
    title = str(state.get("title") or "Initialt läge")
    description = str(
        state.get("description") or "Scenariot har gått in i ett initialt läge."
    )
    known_facts = state.get("known_facts")
    unknowns = state.get("unknowns")
    business_impact = state.get("business_impact")

    key_points: list[str] = []
    if isinstance(known_facts, list):
        key_points.extend(
            [str(item).strip() for item in known_facts if str(item).strip()]
        )
    if isinstance(unknowns, list) and unknowns:
        key_points.append(f"Osäkerhet kvarstår: {str(unknowns[0]).strip()}")
    if len(key_points) < 2 and isinstance(business_impact, list) and business_impact:
        key_points.append(str(business_impact[0]).strip())
    while len(key_points) < 2:
        key_points.append("Lägesbilden behöver fortsatt verifieras.")

    decisions_to_consider = []
    if isinstance(unknowns, list) and unknowns:
        decisions_to_consider.append("Vilken information behöver verifieras först?")
    if isinstance(business_impact, list) and business_impact:
        decisions_to_consider.append(
            "Vilka verksamheter behöver prioriteras omedelbart?"
        )
    if not decisions_to_consider:
        decisions_to_consider.append("Vilken första åtgärd bör prioriteras nu?")

    return {
        "default": {
            "situation_update": f"{title}: {description}",
            "key_points": key_points[:5],
            "new_consequences": [],
            "injects": [],
            "decisions_to_consider": decisions_to_consider[:5],
            "facilitator_notes": (
                "Startnarrativet kompletterades automatiskt för att ge ett giltigt scenarioutkast."
            ),
        }
    }


def _normalize_state_narration(state: dict[str, Any]) -> None:
    narration = state.get("narration")
    if narration is None:
        return

    if isinstance(narration, str):
        text = narration.strip()
        state["narration"] = _narration_config_from_text(text) if text else None
        return

    if not isinstance(narration, dict):
        state["narration"] = None
        return

    default = narration.get("default")
    if isinstance(default, str):
        text = default.strip()
        if text:
            narration["default"] = _narration_payload_from_text(text)
        else:
            narration.pop("default", None)

    by_audience = narration.get("by_audience")
    if isinstance(by_audience, dict):
        for audience, audience_value in list(by_audience.items()):
            if isinstance(audience_value, str):
                text = audience_value.strip()
                if not text:
                    by_audience.pop(audience, None)
                    continue
                by_audience[audience] = _narration_payload_from_text(text)


def _build_key_points_from_text(text: str) -> list[str]:
    parts = [
        part.strip(" -.:;")
        for part in re.split(r"[.!?]\s+|\n+", text)
        if part and part.strip(" -.:;")
    ]
    key_points = parts[:5]
    while len(key_points) < 2:
        key_points.append("Lägesbilden behöver fortsatt verifieras.")
    return key_points


def _narration_payload_from_text(text: str) -> dict[str, Any]:
    return {
        "situation_update": text,
        "key_points": _build_key_points_from_text(text),
        "new_consequences": [],
        "injects": [],
        "decisions_to_consider": [DEFAULT_STATE_DECISION],
        "facilitator_notes": DEFAULT_STATE_NOTES,
    }


def _narration_config_from_text(text: str) -> dict[str, Any]:
    return {"default": _narration_payload_from_text(text)}


def _normalize_entity_ids(
    payload: dict[str, Any], field_name: str, *, fallback_prefix: str
) -> None:
    items = payload.get(field_name)
    if not isinstance(items, list):
        return

    seen_ids: set[str] = set()
    for index, item in enumerate(items):
        if not isinstance(item, dict):
            continue

        item["id"] = _ensure_unique_identifier(
            _sanitize_identifier(
                str(item.get("id") or f"{fallback_prefix}-{index + 1}"),
                fallback=f"{fallback_prefix}-{index + 1}",
            ),
            seen_ids,
        )


def _normalize_executable_rule(
    rule: Any,
    *,
    index: int,
    seen_rule_ids: set[str],
    known_phases: set[str],
) -> dict[str, Any] | None:
    if not isinstance(rule, dict):
        return None

    normalized_rule = dict(rule)
    fallback_rule_id = f"rule-draft-{index + 1}"
    normalized_rule["id"] = _ensure_unique_identifier(
        _sanitize_identifier(
            str(normalized_rule.get("id") or fallback_rule_id),
            fallback=fallback_rule_id,
        ),
        seen_rule_ids,
    )
    normalized_rule["conditions"] = _normalize_rule_conditions(
        normalized_rule.get("conditions")
    )
    normalized_rule["effects"] = _normalize_rule_effects(
        normalized_rule.get("effects"), known_phases
    )
    return normalized_rule


def _is_valid_executable_rule(rule: dict[str, Any]) -> bool:
    has_trigger = isinstance(rule.get("trigger"), str) and bool(rule.get("trigger"))
    has_effects = isinstance(rule.get("effects"), list) and len(rule.get("effects")) > 0
    return has_trigger and has_effects


def _downgrade_rule_to_documentation(
    rule: dict[str, Any], *, index: int
) -> dict[str, Any]:
    return {
        "id": rule["id"],
        "name": str(
            rule.get("name") or rule.get("title") or f"Utkastregel {index + 1}"
        ),
        "conditions": _string_list_from_unknown(rule.get("conditions")),
        "effects": _string_list_from_unknown(rule.get("effects")),
    }


def _string_list_from_unknown(value: Any) -> list[str]:
    if not isinstance(value, list):
        return []

    result: list[str] = []
    for item in value:
        if isinstance(item, str) and item.strip():
            result.append(item.strip())
        elif isinstance(item, dict):
            parts = []
            for key in (
                "type",
                "fact",
                "operator",
                "value",
                "phase",
                "inject_id",
                "item",
                "message",
                "log_type",
            ):
                current = item.get(key)
                if current is not None and str(current).strip():
                    parts.append(f"{key}={current}")
            if parts:
                result.append(", ".join(parts))

    return result


def _normalize_rule_effects(effects: Any, known_phases: set[str]) -> list[Any]:
    if not isinstance(effects, list):
        return []

    normalized_effects: list[Any] = []
    for effect in effects:
        if not isinstance(effect, dict):
            continue

        normalized_effect = dict(effect)
        effect_type = normalized_effect.get("type")
        if not isinstance(effect_type, str):
            continue

        if effect_type == "set_phase":
            phase = normalized_effect.get("phase")
            if not isinstance(phase, str):
                continue
            sanitized_phase = _sanitize_identifier(phase, fallback="")
            if not sanitized_phase or sanitized_phase not in known_phases:
                continue
            normalized_effect["phase"] = sanitized_phase
        elif effect_type in {"add_active_inject", "resolve_inject"}:
            inject_id = normalized_effect.get("inject_id")
            if not isinstance(inject_id, str) or not inject_id.strip():
                fallback_inject_id = normalized_effect.get("value")
                if isinstance(fallback_inject_id, str) and fallback_inject_id.strip():
                    inject_id = fallback_inject_id
            if not isinstance(inject_id, str) or not inject_id.strip():
                continue
            normalized_effect["inject_id"] = _sanitize_identifier(
                inject_id,
                fallback=inject_id,
            )
            normalized_effect.pop("value", None)
        elif effect_type in {"append_focus_item", "append_consequence"}:
            item = normalized_effect.get("item")
            if not isinstance(item, str) or not item.strip():
                continue
            normalized_effect["item"] = item.strip()
        elif effect_type == "increment_metric":
            metric = normalized_effect.get("metric")
            amount = normalized_effect.get("amount")
            if metric not in ALLOWED_METRIC_PATHS or not isinstance(amount, int):
                continue
        elif effect_type == "set_flag":
            flag = normalized_effect.get("flag")
            value = normalized_effect.get("value")
            if flag not in ALLOWED_FLAG_PATHS or not isinstance(value, bool):
                continue
        elif effect_type == "append_exercise_log":
            message = normalized_effect.get("message")
            if not isinstance(message, str) or not message.strip():
                continue
            normalized_effect["message"] = message.strip()
            log_type = normalized_effect.get("log_type")
            if log_type is not None and not (
                isinstance(log_type, str) and log_type.strip()
            ):
                normalized_effect.pop("log_type", None)
        else:
            continue

        normalized_effects.append(normalized_effect)

    return normalized_effects


def _normalize_rule_conditions(conditions: Any) -> list[Any]:
    if not isinstance(conditions, list):
        return []

    normalized_conditions: list[Any] = []
    for condition in conditions:
        if not isinstance(condition, dict):
            continue

        fact = condition.get("fact")
        operator = condition.get("operator")
        value = condition.get("value")

        if fact not in ALLOWED_RULE_FACTS:
            continue
        if operator not in ALLOWED_RULE_OPERATORS:
            continue
        if not isinstance(value, (str, int, bool)):
            continue
        if isinstance(value, str) and not value.strip():
            continue

        normalized_conditions.append(
            {
                "fact": fact,
                "operator": operator,
                "value": value.strip() if isinstance(value, str) else value,
            }
        )

    return normalized_conditions


def _sanitize_identifier(value: str, *, fallback: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii")
    ascii_value = ascii_value.lower()
    ascii_value = re.sub(r"https?://\S+", " ", ascii_value)
    ascii_value = re.sub(r"[^a-z0-9]+", "-", ascii_value)
    ascii_value = ascii_value.strip("-")
    ascii_value = re.sub(r"-{2,}", "-", ascii_value)
    return ascii_value or fallback


def _ensure_unique_identifier(value: str, seen: set[str]) -> str:
    candidate = value
    suffix = 2
    while candidate in seen:
        candidate = f"{value}-{suffix}"
        suffix += 1
    seen.add(candidate)
    return candidate
